version: '3.9'
services:
  fibertemp-db:
    image: mysql:5.7.42
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:${MYSQL_PORT}
    env_file:
      - ./.env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}

  fibertemp-api:
    image: apicopytrader:DEMO
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - fibertemp-db
    env_file:
      - ./.env
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
  
