-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:15:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_sv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_sv` (
  `id` INT NOT NULL,
  `name_user` VARCHAR(255) NULL,
  `sub_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dt_create_account` DATETIME NULL,
  `dt_expired_account` DATETIME NULL,
  `quantidade alerta` VARCHAR(45) NULL,
  `conta valida` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canal` (
  `id` INT NOT NULL,
  `user_sv_id` INT NOT NULL,
  `nome_canal` VARCHAR(45) NULL,
  `dt_create_channel` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_canal_user1_idx` (`user_sv_id` ASC) VISIBLE,
  CONSTRAINT `fk_canal_user1`
    FOREIGN KEY (`user_sv_id`)
    REFERENCES `mydb`.`user_sv` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`all_copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`all_copy` (
  `id` INT NOT NULL,
  `symbol` VARCHAR(45) NULL,
  `action_type` VARCHAR(45) NULL,
  `ticket` VARCHAR(45) NULL,
  `lot` VARCHAR(45) NULL,
  `target_pedding` VARCHAR(45) NULL,
  `takeprofit` VARCHAR(45) NULL,
  `stoploss` VARCHAR(45) NULL,
  `dt_send_order` VARCHAR(45) NULL,
  `user_sv_id` INT NOT NULL,
  `canal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_all_copy_user_idx` (`user_sv_id` ASC) VISIBLE,
  INDEX `fk_all_copy_canal1_idx` (`canal_id` ASC) VISIBLE,
  CONSTRAINT `fk_all_copy_user`
    FOREIGN KEY (`user_sv_id`)
    REFERENCES `mydb`.`user_sv` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_all_copy_canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `mydb`.`canal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_cli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_cli` (
  `id` INT NOT NULL,
  `name_user` VARCHAR(255) NULL,
  `sub_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dt_create_account` DATETIME NULL,
  `dt_expired_account` DATETIME NULL,
  `user_sv_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_cli_user_sv1_idx` (`user_sv_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_cli_user_sv1`
    FOREIGN KEY (`user_sv_id`)
    REFERENCES `mydb`.`user_sv` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permission` (
  `id` INT NOT NULL,
  `isPermission` VARCHAR(45) NULL,
  `user_cli_id` INT NOT NULL,
  `canal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Permission_user_cli1_idx` (`user_cli_id` ASC) VISIBLE,
  INDEX `fk_Permission_canal1_idx` (`canal_id` ASC) VISIBLE,
  CONSTRAINT `fk_Permission_user_cli1`
    FOREIGN KEY (`user_cli_id`)
    REFERENCES `mydb`.`user_cli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permission_canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `mydb`.`canal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`req_copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`req_copy` (
  `id` INT NOT NULL,
  `timer` VARCHAR(45) NULL,
  `canal_id` INT NOT NULL,
  `user_cli_id` INT NOT NULL,
  `all_copy_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_req_copy_canal1_idx` (`canal_id` ASC) VISIBLE,
  INDEX `fk_req_copy_user_cli1_idx` (`user_cli_id` ASC) VISIBLE,
  INDEX `fk_req_copy_all_copy1_idx` (`all_copy_id` ASC) VISIBLE,
  CONSTRAINT `fk_req_copy_canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `mydb`.`canal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_req_copy_user_cli1`
    FOREIGN KEY (`user_cli_id`)
    REFERENCES `mydb`.`user_cli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_req_copy_all_copy1`
    FOREIGN KEY (`all_copy_id`)
    REFERENCES `mydb`.`all_copy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
